name: pebblegenesis
favicon: null
layout_spectrum: 0
typography_spectrum: 0.74462
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#08070c'
    - '#5d3c33'
    - '#877c7b'
    - '#4e617f'
    - '#f1daa8'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
