name: pebblegenesis
favicon: null
layout_spectrum: 0.8688740849029273
typography_spectrum: 0.892610008828342
title: The beginning of Glory
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#08070c'
    - '#5d3c33'
    - '#877c7b'
    - '#4e617f'
    - '#f1daa8'
  brandStrength: 0.9728615062776953
  lightness: 0.8142553546931595
  saturation: 0.28097960562445223
  rhythmicContrast: 0.20943336561322212
purpose: []
