name: pebblegenesis
favicon: null
layout_spectrum: 0.49609
typography_spectrum: 0.74462
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#08070c'
    - '#192845'
    - '#6e4a47'
    - '#81849b'
    - '#ddc585'
  brandStrength: 0
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
