name: pebblegenesis
favicon: null
layout_spectrum: 0.8688740849029273
typography_spectrum: 0.892610008828342
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9728615062776953
  lightness: 0.8142553546931595
  saturation: 0.28097960562445223
  rhythmicContrast: 0.20943336561322212
purpose: []
